# Your SonarQube Cloud organization key
sonar.organization=haruhira
# The key generated when setting up the project on SonarQube Cloud
sonar.projectKey=haru-hira_nest-typeorm

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=nest-typeorm
sonar.projectVersion=1.0

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Excluded files and folders
# sonar.exclusions=node_modules/**/*, test/**/*

# Ignore Issues
# sonar.issue.ignore.multicriteria=e1

# Skip "Use VARCHAR2 instead of VARCHAR." (Because migration SQL cannot be controlled due to automatic generation)
# sonar.issue.ignore.multicriteria.e1.ruleKey=plsql:VarcharUsageCheck
# sonar.issue.ignore.multicriteria.e1.resourceKey=database/migrations/**/*.sql

# Quality gate (fail a pipeline build when the Quality Gate is failing)
sonar.qualitygate.wait=true
