name: Example workflow for Node using Snyk

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        # continue-on-error: true # 脆弱性検出時も後段の処理を続けたい場合に指定
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
