name: Example workflow for Node using Snyk

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  scan_on_sonarqube_cloud:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # 脆弱性検出時も後段の処理を続けたい場合に指定
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # args: test
          command: monitor
      - name: Run Snyk to check IaC files
        uses: snyk/actions/iac@master
        continue-on-error: true # 脆弱性検出時も後段の処理を続けたい場合に指定
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --report
      - name: Run Snyk to check Docker images for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/haru-hira/docker_echo_hello:latest
          command: monitor
  trivy-scanning:
    name: Detect Secrets, Dockerfile Scan, SCA on Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode # スキャンを実行
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs" # ファイルスキャンモード
          scan-ref: "." # スキャンするディレクトリを限定したい場合は変更
          # severity: "CRITICAL,HIGH,MEDIUM" # エラーとする脆弱性のレベル
          format: "table" # 結果をコンソール上に表形式で出力
          exit-code: "0" # 0にすることで脆弱性が検出されてもpipelineを止めない
